changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - ignore-for-release
  categories:
    - title: Breaking Changes 🛠
      labels:
        - done
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - enhancement
    - title: Removing bugs 🐛
      labels:
        - bug
    - title: Other Changes 🚀
      labels:
        - "*"
